name: MLExpert
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=1.4.0=py311hca03da5_0
  - aiohttp=3.9.0=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astroid=3.0.2=py311h267d04e_0
  - astunparse=1.6.3=py_0
  - attrs=23.1.0=py311hca03da5_0
  - black=23.12.1=py311h267d04e_0
  - blas=1.0=openblas
  - blinker=1.6.2=py311hca03da5_0
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.11.17=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=41.0.3=py311h3c57c4d_0
  - dill=0.3.7=pyhd8ed1ab_0
  - flatbuffers=2.0.0=hc377ac9_0
  - frozenlist=1.4.0=py311h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h80987f9_3
  - google-auth=2.22.0=py311hca03da5_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py311h877324c_0
  - h5py=3.9.0=py311hba6ad2f_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - idna=3.4=py311hca03da5_0
  - isort=5.13.2=pyhd8ed1ab_0
  - jpeg=9e=h80987f9_1
  - keras=2.12.0=py311hca03da5_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h8380606_1
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.10.0=h449679c_2
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=14.0.6=hc6e5704_0
  - markdown=3.4.1=py311hca03da5_0
  - markupsafe=2.1.3=py311h80987f9_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - multidict=6.0.4=py311h80987f9_0
  - mypy=1.8.0=py311h05b510d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.23.5=py311hb2c0538_0
  - numpy-base=1.23.5=py311h9eb1c70_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.2=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pip=23.3.1=py311hca03da5_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.7=py311h05b510d_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py311hca03da5_0
  - pylint=3.0.3=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.0=hf452327_1_cpython
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.11=4_cp311
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.11.4=py311hc76d9b0_0
  - setuptools=68.2.2=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h313beb8_1
  - sqlite=3.41.2=h80987f9_0
  - tensorboard=2.12.1=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - tensorflow=2.12.0=eigen_py311h689d69b_0
  - tensorflow-base=2.12.0=eigen_py311h0a52ebb_0
  - tensorflow-estimator=2.12.0=py311hca03da5_0
  - termcolor=2.1.0=py311hca03da5_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h04d1e81_0
  - urllib3=1.26.18=py311hca03da5_0
  - werkzeug=2.2.3=py311hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py311h80987f9_0
  - xz=5.4.5=h80987f9_0
  - yarl=1.9.3=py311h80987f9_0
  - zlib=1.2.13=h53f4e23_5
prefix: /Users/monkey/miniconda3/envs/MLExpert
